//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBuchung
    {
        public int HotelBuchungId { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public int HotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
